# Generated by Django 3.2.8 on 2022-09-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retailer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributeToRetailer',
        ),
    ]
