# Generated by Django 3.2.8 on 2022-09-30 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeToRetailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('total_price', models.CharField(blank=True, max_length=10, null=True)),
                ('calculation_status', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 9, 30))),
            ],
        ),
    ]
