# Generated by Django 3.2.8 on 2022-10-05 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributor', '0002_distributorstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayByDayProductsDistributeToRetailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('retailer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 10, 5))),
            ],
        ),
        migrations.AlterField(
            model_name='distributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 5)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 5)),
        ),
    ]
