# Generated by Django 3.2.8 on 2022-10-06 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributor', '0003_auto_20221005_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybydayproductsdistributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='distributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
    ]
