# Generated by Django 3.2.8 on 2022-10-07 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributor', '0004_auto_20221006_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybydayproductsdistributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 7)),
        ),
        migrations.AlterField(
            model_name='distributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 7)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 7)),
        ),
    ]
