# Generated by Django 3.2.8 on 2022-10-11 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributor', '0006_auto_20221008_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybydayproductsdistributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 11)),
        ),
        migrations.AlterField(
            model_name='distributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 11)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 11)),
        ),
    ]
