# Generated by Django 3.2.8 on 2022-09-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedusers',
            old_name='approved_at',
            new_name='deleted_at',
        ),
    ]
