# Generated by Django 3.2.8 on 2022-09-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0004_auto_20220925_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedusers',
            name='approved_at',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 26)),
        ),
        migrations.AlterField(
            model_name='deletedusers',
            name='deleted_at',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 26)),
        ),
    ]
