# Generated by Django 3.2.8 on 2022-10-13 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0014_auto_20221012_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedusers',
            name='approved_at',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='approvedusers',
            name='email',
            field=models.CharField(blank=True, max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='deletedusers',
            name='deleted_at',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='deletedusers',
            name='email',
            field=models.CharField(blank=True, max_length=46, null=True),
        ),
    ]
