# Generated by Django 3.2.8 on 2022-10-13 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayByDayProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=25, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 10, 13))),
            ],
        ),
        migrations.CreateModel(
            name='DayByDayProductsDistribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 10, 13))),
            ],
        ),
        migrations.CreateModel(
            name='Distribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.CharField(blank=True, max_length=20, null=True)),
                ('calculation_status', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 10, 13))),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('Product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('production_no', models.CharField(blank=True, max_length=20, null=True)),
                ('production_date', models.DateField(verbose_name=datetime.date(2022, 10, 13))),
            ],
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
