# Generated by Django 3.2.8 on 2022-09-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('production_no', models.CharField(blank=True, max_length=150, null=True)),
                ('production_date', models.DateField(verbose_name=datetime.date(2022, 9, 25))),
            ],
        ),
        migrations.CreateModel(
            name='Distribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.CharField(blank=True, max_length=500, null=True)),
                ('calculation_status', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 9, 25))),
            ],
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 9, 25))),
            ],
        ),
    ]
