# Generated by Django 3.2.8 on 2022-09-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturer', '0003_auto_20220925_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('Product_id', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('production_no', models.CharField(blank=True, max_length=10, null=True)),
                ('production_date', models.DateField(verbose_name=datetime.date(2022, 9, 26))),
            ],
        ),
        migrations.DeleteModel(
            name='CreatedProducts',
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 26)),
        ),
        migrations.AlterField(
            model_name='totalproducts',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 26)),
        ),
    ]
