# Generated by Django 3.2.8 on 2022-09-28 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturer', '0004_auto_20220926_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribute',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='totalproducts',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 28)),
        ),
    ]
