# Generated by Django 3.2.8 on 2022-09-29 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturer', '0005_auto_20220928_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayByDayProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=25, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=25, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 9, 29))),
            ],
        ),
        migrations.DeleteModel(
            name='TotalProducts',
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 29)),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 29)),
        ),
    ]
