# Generated by Django 3.2.8 on 2022-09-29 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturer', '0006_auto_20220929_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayByDayProductsDistribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=25, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 9, 29))),
            ],
        ),
    ]
