# Generated by Django 3.2.8 on 2022-09-30 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturer', '0007_daybydayproductsdistribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybydayproducts',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='daybydayproducts',
            name='manufacturer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daybydayproducts',
            name='product_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='daybydayproductsdistribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='daybydayproductsdistribute',
            name='distributor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daybydayproductsdistribute',
            name='manufacturer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daybydayproductsdistribute',
            name='product_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='distributor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='manufacturer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='product_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='Product_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='manufacturer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='Product_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='manufacturer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
