# Generated by Django 3.2.8 on 2022-10-06 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturer', '0009_auto_20221005_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybydayproducts',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='daybydayproductsdistribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='manufacturerstock',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 6)),
        ),
    ]
