# Generated by Django 3.2.8 on 2022-09-13 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=11, null=True)),
                ('role', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.date(2022, 9, 13))),
                ('latitude', models.CharField(blank=True, max_length=12, null=True)),
                ('longitude', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
