# Generated by Django 3.2.8 on 2022-09-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20220913_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='register',
            name='longitude',
        ),
    ]
