# Generated by Django 3.2.8 on 2022-10-13 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_otp_created_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at_time',
            field=models.TimeField(verbose_name=datetime.time(11, 49, 0, 645775)),
        ),
    ]
