# Generated by Django 3.2.8 on 2022-09-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20220913_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='id_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
