# Generated by Django 3.2.8 on 2022-09-13 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_register_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.TimeField(verbose_name=datetime.datetime(2022, 9, 13, 14, 59, 52, 526961))),
            ],
        ),
    ]
