# Generated by Django 3.2.8 on 2022-09-17 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20220917_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 9, 17, 15, 11, 0, 890062)),
        ),
    ]
