# Generated by Django 3.2.8 on 2022-09-25 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_auto_20220925_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 9, 25, 13, 21, 15, 305857)),
        ),
    ]
