# Generated by Django 3.2.8 on 2022-09-25 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 9, 25, 13, 35, 53, 818558)),
        ),
    ]
