# Generated by Django 3.2.8 on 2022-09-29 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_auto_20220929_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 9, 29, 20, 16, 1, 928368)),
        ),
    ]
