# Generated by Django 3.2.8 on 2022-09-30 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_auto_20220930_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 9, 30, 9, 44, 23, 592850)),
        ),
    ]
