# Generated by Django 3.2.8 on 2022-10-06 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_auto_20221006_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 10, 6, 8, 16, 18, 165092)),
        ),
    ]
