# Generated by Django 3.2.8 on 2022-10-07 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='typed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 10, 7, 19, 50, 47, 580919)),
        ),
        migrations.AlterField(
            model_name='register',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 7)),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
