# Generated by Django 3.2.8 on 2022-10-07 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0028_auto_20221007_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='verified',
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 10, 7, 20, 12, 30, 658254)),
        ),
    ]
