# Generated by Django 3.2.8 on 2022-10-07 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0029_auto_20221007_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 10, 7, 20, 22, 45, 59529)),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
