# Generated by Django 3.2.8 on 2022-10-11 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0034_auto_20221008_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at_date',
            field=models.DateField(default=datetime.date(2022, 10, 11)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at_time',
            field=models.TimeField(default=datetime.time(6, 54, 38, 765307)),
        ),
        migrations.AlterField(
            model_name='register',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 11)),
        ),
    ]
