# Generated by Django 3.2.8 on 2022-10-11 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0037_alter_otp_created_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at_time',
            field=models.TimeField(default=datetime.time(6, 55, 45, 477029)),
        ),
    ]
